export type ControlType = "button" | "dial-press" | "dial-turn-right" | "dial-turn-left";

export interface DeckControl {
  id: string;
  type: ControlType;
  position: number;
  label: string;
  description: string;
  isPageNav?: boolean;
  pageNavTarget?: string;
  method?: "POST" | "GET";
  url?: string;
  body?: Record<string, string>;
}

export interface DeckPage {
  id: string;
  label: string;
  buttons: DeckControl[];
  dials: DeckControl[];
}

export const deckPages: DeckPage[] = [
  {
    id: "main",
    label: "MAIN",
    buttons: [
      {
        id: "main-btn-1",
        type: "button",
        position: 1,
        label: "All",
        description: "Set view filter to show all projects",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setFilter", value: "all" },
      },
      {
        id: "main-btn-2",
        type: "button",
        position: 2,
        label: "To Do",
        description: "Filter to To Do column only",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setFilter", value: "todo" },
      },
      {
        id: "main-btn-3",
        type: "button",
        position: 3,
        label: "In Progress",
        description: "Filter to In Progress column only",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setFilter", value: "in-progress" },
      },
      {
        id: "main-btn-4",
        type: "button",
        position: 4,
        label: "→ STATUS",
        description: "Navigate to Status page in Companion",
        isPageNav: true,
        pageNavTarget: "STATUS",
      },
      {
        id: "main-btn-5",
        type: "button",
        position: 5,
        label: "Blocked",
        description: "Filter to Blocked column only",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setFilter", value: "blocked" },
      },
      {
        id: "main-btn-6",
        type: "button",
        position: 6,
        label: "Done",
        description: "Filter to Done column only",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setFilter", value: "done" },
      },
      {
        id: "main-btn-7",
        type: "button",
        position: 7,
        label: "New Project",
        description: "Create a new project",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "createProject" },
      },
      {
        id: "main-btn-8",
        type: "button",
        position: 8,
        label: "→ TASKS",
        description: "Navigate to Tasks page in Companion",
        isPageNav: true,
        pageNavTarget: "TASKS",
      },
    ],
    dials: [
      {
        id: "main-dial-1-press",
        type: "dial-press",
        position: 1,
        label: "Select",
        description: "Press to open project detail",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "openDetail" },
      },
      {
        id: "main-dial-1-right",
        type: "dial-turn-right",
        position: 1,
        label: "Next Project",
        description: "Turn right to select next project",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "next" },
      },
      {
        id: "main-dial-1-left",
        type: "dial-turn-left",
        position: 1,
        label: "Prev Project",
        description: "Turn left to select previous project",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "prev" },
      },
      {
        id: "main-dial-2-press",
        type: "dial-press",
        position: 2,
        label: "Context",
        description: "Press to refresh context (poll endpoint)",
        method: "GET",
        url: "/api/deck/context",
      },
      {
        id: "main-dial-2-right",
        type: "dial-turn-right",
        position: 2,
        label: "Next Project",
        description: "Turn right to select next project (alternate)",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "next" },
      },
      {
        id: "main-dial-2-left",
        type: "dial-turn-left",
        position: 2,
        label: "Prev Project",
        description: "Turn left to select previous project (alternate)",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "prev" },
      },
      {
        id: "main-dial-3-press",
        type: "dial-press",
        position: 3,
        label: "",
        description: "",
      },
      {
        id: "main-dial-4-press",
        type: "dial-press",
        position: 4,
        label: "",
        description: "",
      },
    ],
  },
  {
    id: "status",
    label: "STATUS",
    buttons: [
      {
        id: "status-btn-1",
        type: "button",
        position: 1,
        label: "← MAIN",
        description: "Navigate back to Main page in Companion",
        isPageNav: true,
        pageNavTarget: "MAIN",
      },
      {
        id: "status-btn-2",
        type: "button",
        position: 2,
        label: "To Do",
        description: "Set selected project status to To Do",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setStatus", value: "todo" },
      },
      {
        id: "status-btn-3",
        type: "button",
        position: 3,
        label: "In Progress",
        description: "Set selected project status to In Progress",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setStatus", value: "in-progress" },
      },
      {
        id: "status-btn-4",
        type: "button",
        position: 4,
        label: "→ TASKS",
        description: "Navigate to Tasks page in Companion",
        isPageNav: true,
        pageNavTarget: "TASKS",
      },
      {
        id: "status-btn-5",
        type: "button",
        position: 5,
        label: "Blocked",
        description: "Set selected project status to Blocked",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setStatus", value: "blocked" },
      },
      {
        id: "status-btn-6",
        type: "button",
        position: 6,
        label: "Done",
        description: "Set selected project status to Done",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setStatus", value: "done" },
      },
      {
        id: "status-btn-7",
        type: "button",
        position: 7,
        label: "Cycle Status",
        description: "Cycle to next status value",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "nextStatus" },
      },
      {
        id: "status-btn-8",
        type: "button",
        position: 8,
        label: "Cycle Priority",
        description: "Cycle to next priority value",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "nextPriority" },
      },
    ],
    dials: [
      {
        id: "status-dial-1-press",
        type: "dial-press",
        position: 1,
        label: "Cycle Status",
        description: "Press to cycle project status",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "nextStatus" },
      },
      {
        id: "status-dial-1-right",
        type: "dial-turn-right",
        position: 1,
        label: "Next Project",
        description: "Turn right to select next project",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "next" },
      },
      {
        id: "status-dial-1-left",
        type: "dial-turn-left",
        position: 1,
        label: "Prev Project",
        description: "Turn left to select previous project",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "prev" },
      },
      {
        id: "status-dial-2-press",
        type: "dial-press",
        position: 2,
        label: "Cycle Priority",
        description: "Press to cycle project priority",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "nextPriority" },
      },
      {
        id: "status-dial-2-right",
        type: "dial-turn-right",
        position: 2,
        label: "Next Project",
        description: "Turn right to select next project",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "next" },
      },
      {
        id: "status-dial-2-left",
        type: "dial-turn-left",
        position: 2,
        label: "Prev Project",
        description: "Turn left to select previous project",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "prev" },
      },
      {
        id: "status-dial-3-press",
        type: "dial-press",
        position: 3,
        label: "",
        description: "",
      },
      {
        id: "status-dial-4-press",
        type: "dial-press",
        position: 4,
        label: "",
        description: "",
      },
    ],
  },
  {
    id: "tasks",
    label: "TASKS",
    buttons: [
      {
        id: "tasks-btn-1",
        type: "button",
        position: 1,
        label: "← MAIN",
        description: "Navigate back to Main page in Companion",
        isPageNav: true,
        pageNavTarget: "MAIN",
      },
      {
        id: "tasks-btn-2",
        type: "button",
        position: 2,
        label: "Toggle Timer",
        description: "Start/stop timer on first running or first task",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "toggleTimer" },
      },
      {
        id: "tasks-btn-3",
        type: "button",
        position: 3,
        label: "Complete Task",
        description: "Toggle completion on first incomplete task",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "toggleTaskComplete" },
      },
      {
        id: "tasks-btn-4",
        type: "button",
        position: 4,
        label: "← STATUS",
        description: "Navigate to Status page in Companion",
        isPageNav: true,
        pageNavTarget: "STATUS",
      },
      {
        id: "tasks-btn-5",
        type: "button",
        position: 5,
        label: "Delete Project",
        description: "Delete the currently selected project",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "deleteProject" },
      },
      {
        id: "tasks-btn-6",
        type: "button",
        position: 6,
        label: "",
        description: "",
      },
      {
        id: "tasks-btn-7",
        type: "button",
        position: 7,
        label: "",
        description: "",
      },
      {
        id: "tasks-btn-8",
        type: "button",
        position: 8,
        label: "",
        description: "",
      },
    ],
    dials: [
      {
        id: "tasks-dial-1-press",
        type: "dial-press",
        position: 1,
        label: "Toggle Timer",
        description: "Press to toggle timer",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "toggleTimer" },
      },
      {
        id: "tasks-dial-1-right",
        type: "dial-turn-right",
        position: 1,
        label: "Next Project",
        description: "Turn right to select next project",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "next" },
      },
      {
        id: "tasks-dial-1-left",
        type: "dial-turn-left",
        position: 1,
        label: "Prev Project",
        description: "Turn left to select previous project",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "prev" },
      },
      {
        id: "tasks-dial-2-press",
        type: "dial-press",
        position: 2,
        label: "Complete",
        description: "Press to toggle task completion",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "toggleTaskComplete" },
      },
      {
        id: "tasks-dial-2-right",
        type: "dial-turn-right",
        position: 2,
        label: "Next Project",
        description: "Turn right to select next project",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "next" },
      },
      {
        id: "tasks-dial-2-left",
        type: "dial-turn-left",
        position: 2,
        label: "Prev Project",
        description: "Turn left to select previous project",
        method: "POST",
        url: "/api/deck/select",
        body: { direction: "prev" },
      },
      {
        id: "tasks-dial-3-press",
        type: "dial-press",
        position: 3,
        label: "",
        description: "",
      },
      {
        id: "tasks-dial-4-press",
        type: "dial-press",
        position: 4,
        label: "",
        description: "",
      },
    ],
  },
];

/** Get all interactions for a physical dial (press + turn left + turn right) */
export function getDialInteractions(page: DeckPage, dialPosition: number): DeckControl[] {
  return page.dials.filter((d) => d.position === dialPosition);
}

/** Get unique physical dial positions for a page */
export function getPhysicalDials(page: DeckPage): number[] {
  return Array.from(new Set(page.dials.map((d) => d.position))).sort((a, b) => a - b);
}
