export type ControlType = "button" | "dial-press" | "dial-turn-right" | "dial-turn-left";

export interface DeckControl {
  id: string;
  type: ControlType;
  position: number;
  label: string;
  description: string;
  isPageNav?: boolean;
  pageNavTarget?: string;
  method?: "POST" | "GET";
  url?: string;
  body?: Record<string, string>;
  lcdKey?: string;
  lcdRefreshKeys?: string[];
}

export interface DeckPage {
  id: string;
  label: string;
  buttons: DeckControl[];
  dials: DeckControl[];
}

export const deckPages: DeckPage[] = [
  // ═══════════════════════════════════════════════════════════
  // PAGE 1: PROJECTS
  // ═══════════════════════════════════════════════════════════
  {
    id: "projects",
    label: "PROJECTS",
    buttons: [
      {
        id: "proj-btn-1",
        type: "button",
        position: 1,
        label: "All",
        description: "Set view filter to show all projects",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setFilter", value: "all" },
      },
      {
        id: "proj-btn-2",
        type: "button",
        position: 2,
        label: "To Do",
        description: "Filter to To Do column only",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setFilter", value: "todo" },
      },
      {
        id: "proj-btn-3",
        type: "button",
        position: 3,
        label: "In Prog",
        description: "Filter to In Progress column only",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setFilter", value: "in-progress" },
      },
      {
        id: "proj-btn-4",
        type: "button",
        position: 4,
        label: "TASKS >>",
        description: "Navigate to Tasks page",
        isPageNav: true,
        pageNavTarget: "TASKS",
        lcdRefreshKeys: ["project_nav", "task_nav", "project_status", "project_priority"],
      },
      {
        id: "proj-btn-5",
        type: "button",
        position: 5,
        label: "Blocked",
        description: "Filter to Blocked column only",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setFilter", value: "blocked" },
      },
      {
        id: "proj-btn-6",
        type: "button",
        position: 6,
        label: "Done",
        description: "Filter to Done column only",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setFilter", value: "done" },
      },
      {
        id: "proj-btn-7",
        type: "button",
        position: 7,
        label: "New Proj",
        description: "Create a new project",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "createProject" },
      },
      {
        id: "proj-btn-8",
        type: "button",
        position: 8,
        label: "LIGHTS >>",
        description: "Switch to Light mode",
        isPageNav: true,
        pageNavTarget: "LIGHTS",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "switchToDeckMode", value: "light" },
        lcdRefreshKeys: ["light_nav", "light_intensity", "light_cct", "scene_nav"],
      },
    ],
    dials: [
      // Dial 1: Project navigation
      {
        id: "proj-dial-1-press",
        type: "dial-press",
        position: 1,
        label: "Project",
        description: "Press to open project detail",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "openDetail" },
        lcdKey: "project_nav",
        lcdRefreshKeys: ["project_status", "project_priority", "task_nav", "sort_mode"],
      },
      {
        id: "proj-dial-1-left",
        type: "dial-turn-left",
        position: 1,
        label: "Prev Project",
        description: "Turn left to select previous project",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "selectPrevProject" },
      },
      {
        id: "proj-dial-1-right",
        type: "dial-turn-right",
        position: 1,
        label: "Next Project",
        description: "Turn right to select next project",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "selectNextProject" },
      },
      // Dial 2: Status
      {
        id: "proj-dial-2-press",
        type: "dial-press",
        position: 2,
        label: "Status",
        description: "Press to set status to In Progress",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setStatus", value: "in-progress" },
        lcdKey: "project_status",
      },
      {
        id: "proj-dial-2-left",
        type: "dial-turn-left",
        position: 2,
        label: "Prev Status",
        description: "Turn left to cycle status backward",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "prevStatus" },
      },
      {
        id: "proj-dial-2-right",
        type: "dial-turn-right",
        position: 2,
        label: "Next Status",
        description: "Turn right to cycle status forward",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "nextStatus" },
      },
      // Dial 3: Priority
      {
        id: "proj-dial-3-press",
        type: "dial-press",
        position: 3,
        label: "Priority",
        description: "No action on press",
        lcdKey: "project_priority",
      },
      {
        id: "proj-dial-3-left",
        type: "dial-turn-left",
        position: 3,
        label: "Prev Priority",
        description: "Turn left to cycle priority backward",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "prevPriority" },
      },
      {
        id: "proj-dial-3-right",
        type: "dial-turn-right",
        position: 3,
        label: "Next Priority",
        description: "Turn right to cycle priority forward",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "nextPriority" },
      },
      // Dial 4: Sort
      {
        id: "proj-dial-4-press",
        type: "dial-press",
        position: 4,
        label: "Sort",
        description: "Press to reset sort to manual",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "resetSort" },
        lcdKey: "sort_mode",
      },
      {
        id: "proj-dial-4-left",
        type: "dial-turn-left",
        position: 4,
        label: "Prev Sort",
        description: "Turn left to cycle sort backward",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "prevSort" },
      },
      {
        id: "proj-dial-4-right",
        type: "dial-turn-right",
        position: 4,
        label: "Next Sort",
        description: "Turn right to cycle sort forward",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "nextSort" },
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // PAGE 2: TASKS
  // ═══════════════════════════════════════════════════════════
  {
    id: "tasks",
    label: "TASKS",
    buttons: [
      {
        id: "tasks-btn-1",
        type: "button",
        position: 1,
        label: "<< PROJ",
        description: "Navigate back to Projects page",
        isPageNav: true,
        pageNavTarget: "PROJECTS",
        lcdRefreshKeys: ["project_nav", "project_status", "project_priority", "sort_mode"],
      },
      {
        id: "tasks-btn-2",
        type: "button",
        position: 2,
        label: "Timer",
        description: "Toggle timer on selected task",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "toggleTimer" },
      },
      {
        id: "tasks-btn-3",
        type: "button",
        position: 3,
        label: "Complete",
        description: "Toggle completion on selected task",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "toggleTaskComplete" },
      },
      {
        id: "tasks-btn-4",
        type: "button",
        position: 4,
        label: "In Prog",
        description: "Set project status to In Progress",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setStatus", value: "in-progress" },
      },
      {
        id: "tasks-btn-5",
        type: "button",
        position: 5,
        label: "To Do",
        description: "Set project status to To Do",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setStatus", value: "todo" },
      },
      {
        id: "tasks-btn-6",
        type: "button",
        position: 6,
        label: "Blocked",
        description: "Set project status to Blocked",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setStatus", value: "blocked" },
      },
      {
        id: "tasks-btn-7",
        type: "button",
        position: 7,
        label: "Done",
        description: "Set project status to Done",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setStatus", value: "done" },
      },
      {
        id: "tasks-btn-8",
        type: "button",
        position: 8,
        label: "New Proj",
        description: "Create a new project",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "createProject" },
      },
    ],
    dials: [
      // Dial 1: Project navigation
      {
        id: "tasks-dial-1-press",
        type: "dial-press",
        position: 1,
        label: "Project",
        description: "Press to open project detail",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "openDetail" },
        lcdKey: "project_nav",
        lcdRefreshKeys: ["project_status", "project_priority", "task_nav"],
      },
      {
        id: "tasks-dial-1-left",
        type: "dial-turn-left",
        position: 1,
        label: "Prev Project",
        description: "Turn left to select previous project",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "selectPrevProject" },
      },
      {
        id: "tasks-dial-1-right",
        type: "dial-turn-right",
        position: 1,
        label: "Next Project",
        description: "Turn right to select next project",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "selectNextProject" },
      },
      // Dial 2: Task navigation
      {
        id: "tasks-dial-2-press",
        type: "dial-press",
        position: 2,
        label: "Task",
        description: "Press to toggle timer on selected task",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "toggleTimer" },
        lcdKey: "task_nav",
      },
      {
        id: "tasks-dial-2-left",
        type: "dial-turn-left",
        position: 2,
        label: "Prev Task",
        description: "Turn left to select previous task",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "selectPrevTask" },
      },
      {
        id: "tasks-dial-2-right",
        type: "dial-turn-right",
        position: 2,
        label: "Next Task",
        description: "Turn right to select next task",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "selectNextTask" },
      },
      // Dial 3: Status
      {
        id: "tasks-dial-3-press",
        type: "dial-press",
        position: 3,
        label: "Status",
        description: "Press to set status to In Progress",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "setStatus", value: "in-progress" },
        lcdKey: "project_status",
      },
      {
        id: "tasks-dial-3-left",
        type: "dial-turn-left",
        position: 3,
        label: "Prev Status",
        description: "Turn left to cycle status backward",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "prevStatus" },
      },
      {
        id: "tasks-dial-3-right",
        type: "dial-turn-right",
        position: 3,
        label: "Next Status",
        description: "Turn right to cycle status forward",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "nextStatus" },
      },
      // Dial 4: Priority
      {
        id: "tasks-dial-4-press",
        type: "dial-press",
        position: 4,
        label: "Priority",
        description: "Press to toggle task completion",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "toggleTaskComplete" },
        lcdKey: "project_priority",
      },
      {
        id: "tasks-dial-4-left",
        type: "dial-turn-left",
        position: 4,
        label: "Prev Priority",
        description: "Turn left to cycle priority backward",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "prevPriority" },
      },
      {
        id: "tasks-dial-4-right",
        type: "dial-turn-right",
        position: 4,
        label: "Next Priority",
        description: "Turn right to cycle priority forward",
        method: "POST",
        url: "/api/deck/action",
        body: { action: "nextPriority" },
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // PAGE 3: LIGHTS
  // ═══════════════════════════════════════════════════════════
  {
    id: "lights",
    label: "LIGHTS",
    buttons: [
      {
        id: "lights-btn-1",
        type: "button",
        position: 1,
        label: "<< PROJ",
        description: "Switch back to Project mode",
        isPageNav: true,
        pageNavTarget: "PROJECTS",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "switchToDeckMode", value: "project" },
        lcdRefreshKeys: ["project_nav", "project_status", "project_priority", "sort_mode"],
      },
      {
        id: "lights-btn-2",
        type: "button",
        position: 2,
        label: "Toggle",
        description: "Toggle selected light on/off",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "toggleLight" },
      },
      {
        id: "lights-btn-3",
        type: "button",
        position: 3,
        label: "All On",
        description: "Turn all lights on",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "allOn" },
      },
      {
        id: "lights-btn-4",
        type: "button",
        position: 4,
        label: "All Off",
        description: "Turn all lights off",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "allOff" },
      },
      {
        id: "lights-btn-5",
        type: "button",
        position: 5,
        label: "Save",
        description: "Save current state as scene",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "saveScene" },
      },
      {
        id: "lights-btn-6",
        type: "button",
        position: 6,
        label: "Recall",
        description: "Recall selected scene",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "recallScene" },
      },
      {
        id: "lights-btn-7",
        type: "button",
        position: 7,
        label: "Del Scene",
        description: "Delete selected scene",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "deleteScene" },
      },
      {
        id: "lights-btn-8",
        type: "button",
        position: 8,
        label: "AUDIO >>",
        description: "Switch to Audio mode",
        isPageNav: true,
        pageNavTarget: "AUDIO",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "switchToDeckMode", value: "audio" },
        lcdRefreshKeys: ["audio_ch_nav", "audio_gain1", "audio_gain2", "audio_gain3"],
      },
    ],
    dials: [
      // Dial 1: Light navigation
      {
        id: "lights-dial-1-press",
        type: "dial-press",
        position: 1,
        label: "Light",
        description: "Press to toggle selected light on/off",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "toggleLight" },
        lcdKey: "light_nav",
        lcdRefreshKeys: ["light_intensity", "light_cct"],
      },
      {
        id: "lights-dial-1-left",
        type: "dial-turn-left",
        position: 1,
        label: "Prev Light",
        description: "Turn left to select previous light",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "selectPrevLight" },
      },
      {
        id: "lights-dial-1-right",
        type: "dial-turn-right",
        position: 1,
        label: "Next Light",
        description: "Turn right to select next light",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "selectNextLight" },
      },
      // Dial 2: Intensity
      {
        id: "lights-dial-2-press",
        type: "dial-press",
        position: 2,
        label: "Intensity",
        description: "Press to set intensity to 100%",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "resetIntensity" },
        lcdKey: "light_intensity",
      },
      {
        id: "lights-dial-2-left",
        type: "dial-turn-left",
        position: 2,
        label: "Dim",
        description: "Turn left to decrease intensity",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "intensityDown" },
      },
      {
        id: "lights-dial-2-right",
        type: "dial-turn-right",
        position: 2,
        label: "Brighten",
        description: "Turn right to increase intensity",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "intensityUp" },
      },
      // Dial 3: CCT
      {
        id: "lights-dial-3-press",
        type: "dial-press",
        position: 3,
        label: "CCT",
        description: "Press to reset CCT to 4500K",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "resetCct" },
        lcdKey: "light_cct",
      },
      {
        id: "lights-dial-3-left",
        type: "dial-turn-left",
        position: 3,
        label: "Warmer",
        description: "Turn left to decrease CCT (warmer)",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "cctDown" },
      },
      {
        id: "lights-dial-3-right",
        type: "dial-turn-right",
        position: 3,
        label: "Cooler",
        description: "Turn right to increase CCT (cooler)",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "cctUp" },
      },
      // Dial 4: Scene navigation
      {
        id: "lights-dial-4-press",
        type: "dial-press",
        position: 4,
        label: "Scene",
        description: "Press to recall selected scene",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "recallScene" },
        lcdKey: "scene_nav",
      },
      {
        id: "lights-dial-4-left",
        type: "dial-turn-left",
        position: 4,
        label: "Prev Scene",
        description: "Turn left to select previous scene",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "selectPrevScene" },
      },
      {
        id: "lights-dial-4-right",
        type: "dial-turn-right",
        position: 4,
        label: "Next Scene",
        description: "Turn right to select next scene",
        method: "POST",
        url: "/api/deck/light-action",
        body: { action: "selectNextScene" },
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // PAGE 4: AUDIO
  // ═══════════════════════════════════════════════════════════
  {
    id: "audio",
    label: "AUDIO",
    buttons: [
      {
        id: "audio-btn-1",
        type: "button",
        position: 1,
        label: "<< LIGHTS",
        description: "Switch back to Lights mode",
        isPageNav: true,
        pageNavTarget: "LIGHTS",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "switchToDeckMode", value: "light" },
        lcdRefreshKeys: ["light_nav", "light_intensity", "light_cct", "scene_nav"],
      },
      {
        id: "audio-btn-2",
        type: "button",
        position: 2,
        label: "Mute 1",
        description: "Toggle mute on channel 1",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "toggleMute", value: "1" },
      },
      {
        id: "audio-btn-3",
        type: "button",
        position: 3,
        label: "Mute 2",
        description: "Toggle mute on channel 2",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "toggleMute", value: "2" },
      },
      {
        id: "audio-btn-4",
        type: "button",
        position: 4,
        label: "Mute 3",
        description: "Toggle mute on channel 3",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "toggleMute", value: "3" },
      },
      {
        id: "audio-btn-5",
        type: "button",
        position: 5,
        label: "Mute 4",
        description: "Toggle mute on channel 4",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "toggleMute", value: "4" },
      },
      {
        id: "audio-btn-6",
        type: "button",
        position: 6,
        label: "48V 1",
        description: "Toggle phantom power on channel 1",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "togglePhantom", value: "1" },
      },
      {
        id: "audio-btn-7",
        type: "button",
        position: 7,
        label: "48V 2",
        description: "Toggle phantom power on channel 2",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "togglePhantom", value: "2" },
      },
      {
        id: "audio-btn-8",
        type: "button",
        position: 8,
        label: "Recall",
        description: "Recall selected snapshot",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "recallSnapshot" },
      },
    ],
    dials: [
      // Dial 1: Channel 1 gain
      {
        id: "audio-dial-1-press",
        type: "dial-press",
        position: 1,
        label: "Ch 1",
        description: "Press to toggle mute on channel 1",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "toggleMute", value: "1" },
        lcdKey: "audio_ch_nav",
        lcdRefreshKeys: ["audio_gain1"],
      },
      {
        id: "audio-dial-1-left",
        type: "dial-turn-left",
        position: 1,
        label: "Gain Down",
        description: "Turn left to decrease gain on channel 1",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "gainDown", value: "1" },
      },
      {
        id: "audio-dial-1-right",
        type: "dial-turn-right",
        position: 1,
        label: "Gain Up",
        description: "Turn right to increase gain on channel 1",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "gainUp", value: "1" },
      },
      // Dial 2: Channel 2 gain
      {
        id: "audio-dial-2-press",
        type: "dial-press",
        position: 2,
        label: "Ch 2",
        description: "Press to toggle mute on channel 2",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "toggleMute", value: "2" },
        lcdKey: "audio_gain1",
      },
      {
        id: "audio-dial-2-left",
        type: "dial-turn-left",
        position: 2,
        label: "Gain Down",
        description: "Turn left to decrease gain on channel 2",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "gainDown", value: "2" },
      },
      {
        id: "audio-dial-2-right",
        type: "dial-turn-right",
        position: 2,
        label: "Gain Up",
        description: "Turn right to increase gain on channel 2",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "gainUp", value: "2" },
      },
      // Dial 3: Channel 3 gain
      {
        id: "audio-dial-3-press",
        type: "dial-press",
        position: 3,
        label: "Ch 3",
        description: "Press to toggle mute on channel 3",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "toggleMute", value: "3" },
        lcdKey: "audio_gain2",
      },
      {
        id: "audio-dial-3-left",
        type: "dial-turn-left",
        position: 3,
        label: "Gain Down",
        description: "Turn left to decrease gain on channel 3",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "gainDown", value: "3" },
      },
      {
        id: "audio-dial-3-right",
        type: "dial-turn-right",
        position: 3,
        label: "Gain Up",
        description: "Turn right to increase gain on channel 3",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "gainUp", value: "3" },
      },
      // Dial 4: Channel 4 gain
      {
        id: "audio-dial-4-press",
        type: "dial-press",
        position: 4,
        label: "Ch 4",
        description: "Press to toggle mute on channel 4",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "toggleMute", value: "4" },
        lcdKey: "audio_gain3",
      },
      {
        id: "audio-dial-4-left",
        type: "dial-turn-left",
        position: 4,
        label: "Gain Down",
        description: "Turn left to decrease gain on channel 4",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "gainDown", value: "4" },
      },
      {
        id: "audio-dial-4-right",
        type: "dial-turn-right",
        position: 4,
        label: "Gain Up",
        description: "Turn right to increase gain on channel 4",
        method: "POST",
        url: "/api/deck/audio-action",
        body: { action: "gainUp", value: "4" },
      },
    ],
  },
];

/** Get all interactions for a physical dial (press + turn left + turn right) */
export function getDialInteractions(page: DeckPage, dialPosition: number): DeckControl[] {
  return page.dials.filter((d) => d.position === dialPosition);
}

/** Get unique physical dial positions for a page */
export function getPhysicalDials(page: DeckPage): number[] {
  return Array.from(new Set(page.dials.map((d) => d.position))).sort((a, b) => a - b);
}
