import type { DB } from "./types";

interface SeedOptions {
  /** Include sample lights, scenes, and lighting settings. Default: false. */
  includeLights?: boolean;
}

export function buildSeedData(options?: SeedOptions): DB {
  const now = new Date().toISOString();
  const includeLights = options?.includeLights ?? false;

  return {
    schemaVersion: 7,
    projects: [
      {
        id: "proj-1",
        title: "Website Redesign",
        description: "Complete overhaul of the marketing site with new branding.",
        status: "in-progress",
        priority: "p1",
        createdAt: now,
        lastUpdated: now,
        order: 0,
      },
      {
        id: "proj-2",
        title: "API Integration",
        description: "Integrate third-party payment and analytics APIs.",
        status: "todo",
        priority: "p2",
        createdAt: now,
        lastUpdated: now,
        order: 1,
      },
      {
        id: "proj-3",
        title: "Database Migration",
        description: "Migrate from legacy schema to normalized structure.",
        status: "blocked",
        priority: "p0",
        createdAt: now,
        lastUpdated: now,
        order: 2,
      },
      {
        id: "proj-4",
        title: "Auth Refactor",
        description: "Replace session-based auth with JWT tokens.",
        status: "done",
        priority: "p3",
        createdAt: now,
        lastUpdated: now,
        order: 3,
      },
    ],
    tasks: [
      {
        id: "task-1",
        projectId: "proj-1",
        title: "Design mockups",
        description: "Create Figma mockups for all key pages.",
        priority: "p1",
        dueDate: null,
        labels: ["design"],
        checklist: [
          { id: "cl-1", text: "Homepage layout", done: true },
          { id: "cl-2", text: "About page", done: true },
          { id: "cl-3", text: "Contact form", done: false },
        ],
        isRunning: false,
        totalSeconds: 3600,
        lastStarted: null,
        completed: true,
        order: 0,
        createdAt: now,
      },
      {
        id: "task-2",
        projectId: "proj-1",
        title: "Implement components",
        description: "Build React components from approved mockups.",
        priority: "p1",
        dueDate: "2026-03-25",
        labels: ["frontend"],
        checklist: [],
        isRunning: false,
        totalSeconds: 0,
        lastStarted: null,
        completed: false,
        order: 1,
        createdAt: now,
      },
      {
        id: "task-3",
        projectId: "proj-2",
        title: "Research endpoints",
        description: "Document available API endpoints and rate limits.",
        priority: "p2",
        dueDate: "2026-03-20",
        labels: ["research"],
        checklist: [],
        isRunning: false,
        totalSeconds: 1800,
        lastStarted: null,
        completed: false,
        order: 0,
        createdAt: now,
      },
      {
        id: "task-4",
        projectId: "proj-3",
        title: "Write migration scripts",
        description: "SQL migration scripts for schema changes.",
        priority: "p0",
        dueDate: null,
        labels: ["backend", "database"],
        checklist: [],
        isRunning: false,
        totalSeconds: 900,
        lastStarted: null,
        completed: false,
        order: 0,
        createdAt: now,
      },
      {
        id: "task-5",
        projectId: "proj-4",
        title: "Update JWT handling",
        description: "Implement token refresh and revocation.",
        priority: "p2",
        dueDate: null,
        labels: ["auth"],
        checklist: [],
        isRunning: false,
        totalSeconds: 7200,
        lastStarted: null,
        completed: true,
        order: 0,
        createdAt: now,
      },
    ],
    activityLog: [
      {
        id: "act-seed-1",
        timestamp: now,
        entityType: "project",
        entityId: "proj-1",
        action: "status_changed",
        detail: "Status set to in-progress",
      },
      {
        id: "act-seed-2",
        timestamp: now,
        entityType: "task",
        entityId: "task-1",
        action: "completed",
        detail: "Task marked as completed",
      },
    ],
    settings: {
      viewFilter: "all",
      sortBy: "manual",
      selectedProjectId: null,
      selectedTaskId: null,
      dashboardView: "kanban",
      deckMode: "project",
      hasCompletedSetup: false,
    },
    lights: includeLights
      ? [
          {
            id: "light-1",
            name: "Key Left",
            type: "astra-bicolor",
            dmxStartAddress: 1,
            intensity: 85,
            cct: 4400,
            on: true,
            order: 0,
            red: 0,
            green: 0,
            blue: 0,
            colorMode: "cct",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.3,
            spatialY: 0.25,
            spatialRotation: 180,
          },
          {
            id: "light-2",
            name: "Key Right",
            type: "astra-bicolor",
            dmxStartAddress: 3,
            intensity: 75,
            cct: 4400,
            on: true,
            order: 1,
            red: 0,
            green: 0,
            blue: 0,
            colorMode: "cct",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.7,
            spatialY: 0.25,
            spatialRotation: 180,
          },
          {
            id: "light-3",
            name: "Fill",
            type: "astra-bicolor",
            dmxStartAddress: 5,
            intensity: 50,
            cct: 5000,
            on: true,
            order: 2,
            red: 0,
            green: 0,
            blue: 0,
            colorMode: "cct",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.5,
            spatialY: 0.15,
            spatialRotation: 180,
          },
          {
            id: "light-4",
            name: "Background",
            type: "infinimat",
            dmxStartAddress: 7,
            intensity: 40,
            cct: 5600,
            on: true,
            order: 3,
            red: 0,
            green: 0,
            blue: 0,
            colorMode: "cct",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.5,
            spatialY: 0.85,
            spatialRotation: 0,
          },
          {
            id: "light-5",
            name: "BG Bar 1",
            type: "infinibar-pb12",
            dmxStartAddress: 11,
            intensity: 60,
            cct: 5600,
            on: true,
            order: 4,
            red: 0,
            green: 100,
            blue: 200,
            colorMode: "rgb",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.2,
            spatialY: 0.85,
            spatialRotation: 0,
          },
          {
            id: "light-6",
            name: "BG Bar 2",
            type: "infinibar-pb12",
            dmxStartAddress: 19,
            intensity: 60,
            cct: 5600,
            on: true,
            order: 5,
            red: 0,
            green: 100,
            blue: 200,
            colorMode: "rgb",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.4,
            spatialY: 0.85,
            spatialRotation: 0,
          },
          {
            id: "light-7",
            name: "BG Bar 3",
            type: "infinibar-pb12",
            dmxStartAddress: 27,
            intensity: 50,
            cct: 5600,
            on: true,
            order: 6,
            red: 100,
            green: 0,
            blue: 150,
            colorMode: "rgb",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.6,
            spatialY: 0.85,
            spatialRotation: 0,
          },
          {
            id: "light-8",
            name: "BG Bar 4",
            type: "infinibar-pb12",
            dmxStartAddress: 35,
            intensity: 50,
            cct: 5600,
            on: true,
            order: 7,
            red: 100,
            green: 0,
            blue: 150,
            colorMode: "rgb",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.8,
            spatialY: 0.85,
            spatialRotation: 0,
          },
        ]
      : [],
    lightGroups: [],
    lightScenes: includeLights
      ? [
          {
            id: "scene-1",
            name: "Interview",
            lightStates: [
              {
                lightId: "light-1",
                intensity: 85,
                cct: 4400,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-2",
                intensity: 75,
                cct: 4400,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-3",
                intensity: 50,
                cct: 5000,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-4",
                intensity: 40,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-5",
                intensity: 50,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-6",
                intensity: 50,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-7",
                intensity: 40,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-8",
                intensity: 40,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
            ],
            createdAt: now,
            order: 0,
          },
          {
            id: "scene-2",
            name: "Product Shot",
            lightStates: [
              {
                lightId: "light-1",
                intensity: 100,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-2",
                intensity: 100,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-3",
                intensity: 70,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-4",
                intensity: 50,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-5",
                intensity: 80,
                cct: 5600,
                on: true,
                red: 255,
                green: 255,
                blue: 255,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-6",
                intensity: 80,
                cct: 5600,
                on: true,
                red: 255,
                green: 255,
                blue: 255,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-7",
                intensity: 80,
                cct: 5600,
                on: true,
                red: 255,
                green: 255,
                blue: 255,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-8",
                intensity: 80,
                cct: 5600,
                on: true,
                red: 255,
                green: 255,
                blue: 255,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
            ],
            createdAt: now,
            order: 1,
          },
          {
            id: "scene-3",
            name: "Moody",
            lightStates: [
              {
                lightId: "light-1",
                intensity: 60,
                cct: 3200,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-2",
                intensity: 0,
                cct: 3200,
                on: false,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-3",
                intensity: 30,
                cct: 3200,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-4",
                intensity: 20,
                cct: 3000,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-5",
                intensity: 40,
                cct: 2000,
                on: true,
                red: 150,
                green: 0,
                blue: 200,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-6",
                intensity: 40,
                cct: 2000,
                on: true,
                red: 150,
                green: 0,
                blue: 200,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-7",
                intensity: 30,
                cct: 2000,
                on: true,
                red: 100,
                green: 0,
                blue: 150,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-8",
                intensity: 30,
                cct: 2000,
                on: true,
                red: 100,
                green: 0,
                blue: 150,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
            ],
            createdAt: now,
            order: 2,
          },
        ]
      : [],
    lightingSettings: {
      apolloBridgeIp: "2.0.0.1",
      dmxUniverse: 1,
      dmxEnabled: false,
      selectedLightId: null,
      selectedSceneId: null,
      grandMaster: 100,
      cameraMarker: null,
      subjectMarker: null,
    },
    audioChannels: [
      {
        id: "audio-ch-1",
        name: "Presenter",
        oscChannel: 1,
        order: 0,
        gain: 45,
        fader: 0.75,
        mute: false,
        solo: false,
        phantom: true,
        phase: false,
        pad: false,
        loCut: true,
      },
      {
        id: "audio-ch-2",
        name: "Guest",
        oscChannel: 2,
        order: 1,
        gain: 40,
        fader: 0.7,
        mute: false,
        solo: false,
        phantom: true,
        phase: false,
        pad: false,
        loCut: true,
      },
      {
        id: "audio-ch-3",
        name: "Lapel 3",
        oscChannel: 3,
        order: 2,
        gain: 35,
        fader: 0.65,
        mute: true,
        solo: false,
        phantom: true,
        phase: false,
        pad: false,
        loCut: false,
      },
      {
        id: "audio-ch-4",
        name: "Lapel 4",
        oscChannel: 4,
        order: 3,
        gain: 35,
        fader: 0.65,
        mute: true,
        solo: false,
        phantom: true,
        phase: false,
        pad: false,
        loCut: false,
      },
    ],
    audioSnapshots: [
      {
        id: "asnap-1",
        name: "Interview Setup",
        oscIndex: 0,
        order: 0,
      },
      {
        id: "asnap-2",
        name: "Solo Podcast",
        oscIndex: 1,
        order: 1,
      },
    ],
    audioSettings: {
      oscEnabled: false,
      oscSendHost: "127.0.0.1",
      oscSendPort: 7001,
      oscReceivePort: 9001,
      selectedChannelId: null,
    },
  };
}
