import type { DB } from "./types";
import {
  AUDIO_MIX_TARGET_IDS,
  createDefaultAudioChannels,
  createDefaultAudioMixTargets,
  createDefaultAudioSettings,
} from "./audio-console";

interface SeedOptions {
  /** Include sample lights, scenes, and lighting settings. Default: false. */
  includeLights?: boolean;
}

export function buildSeedData(options?: SeedOptions): DB {
  const now = new Date().toISOString();
  const includeLights = options?.includeLights ?? false;
  const audioChannels = createDefaultAudioChannels().map((channel) => {
    const overrides: Record<string, Partial<DB["audioChannels"][number]>> = {
      "audio-input-9": {
        name: "Host",
        shortName: "HOST",
        gain: 43,
        phantom: true,
        autoSet: true,
        fader: 0.78,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.78,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.72,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.68,
        },
      },
      "audio-input-10": {
        name: "Guest",
        shortName: "GST",
        gain: 40,
        phantom: true,
        fader: 0.76,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.76,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.69,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.66,
        },
      },
      "audio-input-11": {
        name: "Boom",
        shortName: "BOOM",
        gain: 32,
        phantom: true,
        fader: 0.72,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.72,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.74,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.7,
        },
      },
      "audio-input-12": {
        name: "Guitar DI",
        shortName: "GTR DI",
        gain: 28,
        instrument: true,
        fader: 0.54,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.54,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.62,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.58,
        },
      },
      "audio-input-1": {
        name: "Line 1",
        shortName: "L1",
        fader: 0.64,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.64,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.48,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.44,
        },
      },
      "audio-input-2": {
        name: "Line 2",
        shortName: "L2",
        fader: 0.64,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.64,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.46,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.42,
        },
      },
      "audio-input-3": {
        name: "Remote A",
        shortName: "REM A",
        mute: true,
        fader: 0.58,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.58,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.51,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.49,
        },
      },
      "audio-input-4": {
        name: "Remote B",
        shortName: "REM B",
        mute: true,
        fader: 0.58,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.58,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.5,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.48,
        },
      },
      "audio-playback-1-2": {
        name: "Program 1/2",
        shortName: "PGM",
        fader: 0.64,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.64,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.58,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.55,
        },
      },
      "audio-playback-3-4": {
        name: "FX 3/4",
        shortName: "FX",
        fader: 0.48,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.48,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.36,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.34,
        },
      },
      "audio-playback-5-6": {
        name: "N-1 5/6",
        shortName: "N-1",
        fader: 0.44,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.44,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.68,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.64,
        },
      },
      "audio-playback-7-8": {
        name: "Music 7/8",
        shortName: "MUS",
        fader: 0.4,
        mixLevels: {
          [AUDIO_MIX_TARGET_IDS.main]: 0.4,
          [AUDIO_MIX_TARGET_IDS.phonesA]: 0.58,
          [AUDIO_MIX_TARGET_IDS.phonesB]: 0.54,
        },
      },
    };

    return {
      ...channel,
      ...(overrides[channel.id] ?? {}),
    };
  });

  const audioMixTargets = createDefaultAudioMixTargets().map((target) => {
    switch (target.id) {
      case "audio-mix-main":
        return { ...target, volume: 0.82 };
      case "audio-mix-phones-a":
        return { ...target, volume: 0.74 };
      case "audio-mix-phones-b":
        return { ...target, volume: 0.71 };
      default:
        return target;
    }
  });

  const audioSettings = {
    ...createDefaultAudioSettings(),
    selectedChannelId: "audio-input-9",
    selectedMixTargetId: "audio-mix-main",
  };

  return {
    schemaVersion: 8,
    projects: [
      {
        id: "proj-1",
        title: "Website Redesign",
        description: "Complete overhaul of the marketing site with new branding.",
        status: "in-progress",
        priority: "p1",
        createdAt: now,
        lastUpdated: now,
        order: 0,
      },
      {
        id: "proj-2",
        title: "API Integration",
        description: "Integrate third-party payment and analytics APIs.",
        status: "todo",
        priority: "p2",
        createdAt: now,
        lastUpdated: now,
        order: 1,
      },
      {
        id: "proj-3",
        title: "Database Migration",
        description: "Migrate from legacy schema to normalized structure.",
        status: "blocked",
        priority: "p0",
        createdAt: now,
        lastUpdated: now,
        order: 2,
      },
      {
        id: "proj-4",
        title: "Auth Refactor",
        description: "Replace session-based auth with JWT tokens.",
        status: "done",
        priority: "p3",
        createdAt: now,
        lastUpdated: now,
        order: 3,
      },
    ],
    tasks: [
      {
        id: "task-1",
        projectId: "proj-1",
        title: "Design mockups",
        description: "Create Figma mockups for all key pages.",
        priority: "p1",
        dueDate: null,
        labels: ["design"],
        checklist: [
          { id: "cl-1", text: "Homepage layout", done: true },
          { id: "cl-2", text: "About page", done: true },
          { id: "cl-3", text: "Contact form", done: false },
        ],
        isRunning: false,
        totalSeconds: 3600,
        lastStarted: null,
        completed: true,
        order: 0,
        createdAt: now,
      },
      {
        id: "task-2",
        projectId: "proj-1",
        title: "Implement components",
        description: "Build React components from approved mockups.",
        priority: "p1",
        dueDate: "2026-03-25",
        labels: ["frontend"],
        checklist: [],
        isRunning: false,
        totalSeconds: 0,
        lastStarted: null,
        completed: false,
        order: 1,
        createdAt: now,
      },
      {
        id: "task-3",
        projectId: "proj-2",
        title: "Research endpoints",
        description: "Document available API endpoints and rate limits.",
        priority: "p2",
        dueDate: "2026-03-20",
        labels: ["research"],
        checklist: [],
        isRunning: false,
        totalSeconds: 1800,
        lastStarted: null,
        completed: false,
        order: 0,
        createdAt: now,
      },
      {
        id: "task-4",
        projectId: "proj-3",
        title: "Write migration scripts",
        description: "SQL migration scripts for schema changes.",
        priority: "p0",
        dueDate: null,
        labels: ["backend", "database"],
        checklist: [],
        isRunning: false,
        totalSeconds: 900,
        lastStarted: null,
        completed: false,
        order: 0,
        createdAt: now,
      },
      {
        id: "task-5",
        projectId: "proj-4",
        title: "Update JWT handling",
        description: "Implement token refresh and revocation.",
        priority: "p2",
        dueDate: null,
        labels: ["auth"],
        checklist: [],
        isRunning: false,
        totalSeconds: 7200,
        lastStarted: null,
        completed: true,
        order: 0,
        createdAt: now,
      },
    ],
    activityLog: [
      {
        id: "act-seed-1",
        timestamp: now,
        entityType: "project",
        entityId: "proj-1",
        action: "status_changed",
        detail: "Status set to in-progress",
      },
      {
        id: "act-seed-2",
        timestamp: now,
        entityType: "task",
        entityId: "task-1",
        action: "completed",
        detail: "Task marked as completed",
      },
    ],
    settings: {
      viewFilter: "all",
      sortBy: "manual",
      selectedProjectId: null,
      selectedTaskId: null,
      dashboardView: "kanban",
      deckMode: "project",
      hasCompletedSetup: false,
    },
    lights: includeLights
      ? [
          {
            id: "light-1",
            name: "Key Left",
            type: "astra-bicolor",
            dmxStartAddress: 1,
            intensity: 85,
            cct: 4400,
            on: true,
            order: 0,
            red: 0,
            green: 0,
            blue: 0,
            colorMode: "cct",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.3,
            spatialY: 0.25,
            spatialRotation: 180,
          },
          {
            id: "light-2",
            name: "Key Right",
            type: "astra-bicolor",
            dmxStartAddress: 3,
            intensity: 75,
            cct: 4400,
            on: true,
            order: 1,
            red: 0,
            green: 0,
            blue: 0,
            colorMode: "cct",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.7,
            spatialY: 0.25,
            spatialRotation: 180,
          },
          {
            id: "light-3",
            name: "Fill",
            type: "astra-bicolor",
            dmxStartAddress: 5,
            intensity: 50,
            cct: 5000,
            on: true,
            order: 2,
            red: 0,
            green: 0,
            blue: 0,
            colorMode: "cct",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.5,
            spatialY: 0.15,
            spatialRotation: 180,
          },
          {
            id: "light-4",
            name: "Background",
            type: "infinimat",
            dmxStartAddress: 7,
            intensity: 40,
            cct: 5600,
            on: true,
            order: 3,
            red: 0,
            green: 0,
            blue: 0,
            colorMode: "cct",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.5,
            spatialY: 0.85,
            spatialRotation: 0,
          },
          {
            id: "light-5",
            name: "BG Bar 1",
            type: "infinibar-pb12",
            dmxStartAddress: 11,
            intensity: 60,
            cct: 5600,
            on: true,
            order: 4,
            red: 0,
            green: 100,
            blue: 200,
            colorMode: "rgb",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.2,
            spatialY: 0.85,
            spatialRotation: 0,
          },
          {
            id: "light-6",
            name: "BG Bar 2",
            type: "infinibar-pb12",
            dmxStartAddress: 19,
            intensity: 60,
            cct: 5600,
            on: true,
            order: 5,
            red: 0,
            green: 100,
            blue: 200,
            colorMode: "rgb",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.4,
            spatialY: 0.85,
            spatialRotation: 0,
          },
          {
            id: "light-7",
            name: "BG Bar 3",
            type: "infinibar-pb12",
            dmxStartAddress: 27,
            intensity: 50,
            cct: 5600,
            on: true,
            order: 6,
            red: 100,
            green: 0,
            blue: 150,
            colorMode: "rgb",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.6,
            spatialY: 0.85,
            spatialRotation: 0,
          },
          {
            id: "light-8",
            name: "BG Bar 4",
            type: "infinibar-pb12",
            dmxStartAddress: 35,
            intensity: 50,
            cct: 5600,
            on: true,
            order: 7,
            red: 100,
            green: 0,
            blue: 150,
            colorMode: "rgb",
            gmTint: 0,
            groupId: null,
            effect: null,
            spatialX: 0.8,
            spatialY: 0.85,
            spatialRotation: 0,
          },
        ]
      : [],
    lightGroups: [],
    lightScenes: includeLights
      ? [
          {
            id: "scene-1",
            name: "Interview",
            lightStates: [
              {
                lightId: "light-1",
                intensity: 85,
                cct: 4400,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-2",
                intensity: 75,
                cct: 4400,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-3",
                intensity: 50,
                cct: 5000,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-4",
                intensity: 40,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-5",
                intensity: 50,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-6",
                intensity: 50,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-7",
                intensity: 40,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-8",
                intensity: 40,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
            ],
            createdAt: now,
            order: 0,
          },
          {
            id: "scene-2",
            name: "Product Shot",
            lightStates: [
              {
                lightId: "light-1",
                intensity: 100,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-2",
                intensity: 100,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-3",
                intensity: 70,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-4",
                intensity: 50,
                cct: 5600,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-5",
                intensity: 80,
                cct: 5600,
                on: true,
                red: 255,
                green: 255,
                blue: 255,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-6",
                intensity: 80,
                cct: 5600,
                on: true,
                red: 255,
                green: 255,
                blue: 255,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-7",
                intensity: 80,
                cct: 5600,
                on: true,
                red: 255,
                green: 255,
                blue: 255,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-8",
                intensity: 80,
                cct: 5600,
                on: true,
                red: 255,
                green: 255,
                blue: 255,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
            ],
            createdAt: now,
            order: 1,
          },
          {
            id: "scene-3",
            name: "Moody",
            lightStates: [
              {
                lightId: "light-1",
                intensity: 60,
                cct: 3200,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-2",
                intensity: 0,
                cct: 3200,
                on: false,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-3",
                intensity: 30,
                cct: 3200,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-4",
                intensity: 20,
                cct: 3000,
                on: true,
                red: 0,
                green: 0,
                blue: 0,
                colorMode: "cct" as const,
                gmTint: 0,
              },
              {
                lightId: "light-5",
                intensity: 40,
                cct: 2000,
                on: true,
                red: 150,
                green: 0,
                blue: 200,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-6",
                intensity: 40,
                cct: 2000,
                on: true,
                red: 150,
                green: 0,
                blue: 200,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-7",
                intensity: 30,
                cct: 2000,
                on: true,
                red: 100,
                green: 0,
                blue: 150,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
              {
                lightId: "light-8",
                intensity: 30,
                cct: 2000,
                on: true,
                red: 100,
                green: 0,
                blue: 150,
                colorMode: "rgb" as const,
                gmTint: 0,
              },
            ],
            createdAt: now,
            order: 2,
          },
        ]
      : [],
    lightingSettings: {
      apolloBridgeIp: "2.0.0.1",
      dmxUniverse: 1,
      dmxEnabled: false,
      selectedLightId: null,
      selectedSceneId: null,
      grandMaster: 100,
      cameraMarker: null,
      subjectMarker: null,
    },
    audioChannels,
    audioMixTargets,
    audioSnapshots: [
      {
        id: "asnap-1",
        name: "Interview Setup",
        oscIndex: 0,
        order: 0,
      },
      {
        id: "asnap-2",
        name: "Solo Podcast",
        oscIndex: 1,
        order: 1,
      },
    ],
    audioSettings,
  };
}
