import fs from "fs";
import path from "path";
import type { DB } from "../lib/types";

const now = new Date().toISOString();

const db: DB = {
  projects: [
    {
      id: "proj-1",
      title: "Website Redesign",
      description: "Complete overhaul of the marketing site with new branding.",
      status: "in-progress",
      priority: "p1",
      createdAt: now,
      lastUpdated: now,
      order: 0,
    },
    {
      id: "proj-2",
      title: "API Integration",
      description: "Integrate third-party payment and analytics APIs.",
      status: "todo",
      priority: "p2",
      createdAt: now,
      lastUpdated: now,
      order: 1,
    },
    {
      id: "proj-3",
      title: "Database Migration",
      description: "Migrate from legacy schema to normalized structure.",
      status: "blocked",
      priority: "p0",
      createdAt: now,
      lastUpdated: now,
      order: 2,
    },
    {
      id: "proj-4",
      title: "Auth Refactor",
      description: "Replace session-based auth with JWT tokens.",
      status: "done",
      priority: "p3",
      createdAt: now,
      lastUpdated: now,
      order: 3,
    },
  ],
  tasks: [
    {
      id: "task-1",
      projectId: "proj-1",
      title: "Design mockups",
      description: "Create Figma mockups for all key pages.",
      priority: "p1",
      dueDate: null,
      labels: ["design"],
      isRunning: false,
      totalSeconds: 3600,
      lastStarted: null,
      completed: true,
      order: 0,
      createdAt: now,
    },
    {
      id: "task-2",
      projectId: "proj-1",
      title: "Implement components",
      description: "Build React components from approved mockups.",
      priority: "p1",
      dueDate: "2026-03-25",
      labels: ["frontend"],
      isRunning: false,
      totalSeconds: 0,
      lastStarted: null,
      completed: false,
      order: 1,
      createdAt: now,
    },
    {
      id: "task-3",
      projectId: "proj-2",
      title: "Research endpoints",
      description: "Document available API endpoints and rate limits.",
      priority: "p2",
      dueDate: "2026-03-20",
      labels: ["research"],
      isRunning: false,
      totalSeconds: 1800,
      lastStarted: null,
      completed: false,
      order: 0,
      createdAt: now,
    },
    {
      id: "task-4",
      projectId: "proj-3",
      title: "Write migration scripts",
      description: "SQL migration scripts for schema changes.",
      priority: "p0",
      dueDate: null,
      labels: ["backend", "database"],
      isRunning: false,
      totalSeconds: 900,
      lastStarted: null,
      completed: false,
      order: 0,
      createdAt: now,
    },
    {
      id: "task-5",
      projectId: "proj-4",
      title: "Update JWT handling",
      description: "Implement token refresh and revocation.",
      priority: "p2",
      dueDate: null,
      labels: ["auth"],
      isRunning: false,
      totalSeconds: 7200,
      lastStarted: null,
      completed: true,
      order: 0,
      createdAt: now,
    },
  ],
  activityLog: [
    {
      id: "act-seed-1",
      timestamp: now,
      entityType: "project",
      entityId: "proj-1",
      action: "status_changed",
      detail: "Status set to in-progress",
    },
    {
      id: "act-seed-2",
      timestamp: now,
      entityType: "task",
      entityId: "task-1",
      action: "completed",
      detail: "Task marked as completed",
    },
  ],
  settings: {
    viewFilter: "all",
    sortBy: "manual",
    selectedProjectId: null,
  },
};

const dbPath = path.join(process.cwd(), "data", "db.json");
const dir = path.dirname(dbPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(dbPath, JSON.stringify(db, null, 2));
console.log("Seeded data/db.json");
